
- name: Manage docker on fedora linux
  hosts: fedora_servers
  become: yes

  tasks:

    - name: Install packages
      dnf: 
        name:
          - dnf-pluigns-core
          - docker
        state: present
