
- name: Manage docker on fedora linux
  hosts: fedora_servers
  become: yes

  tasks:

    - name: Install packages
      dnf: 
        name:
          - dnf-pluigns-core
          - docker
        state: present

    - name: Enable and start docker
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Is pip install
      dnf:
        name: python3-pip
        state: present
        




