name: Test Ansible Docker Playbook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible python3-pip
        pip3 install docker
        ansible --version

    - name: Install Ansible docker collection
      run: |
        ansible-galaxy collection install community.docker

    - name: Start Docker service inside runner
      run: |
        sudo systemctl start docker
        docker info

    - name: Run Ansible playbook (local mode)
      run: |
        ansible-playbook playbook.yml -i localhost, --connection=local

    - name: Test container is running
      run: |
        docker ps





